server:
  port: 8888
spring:
  application:
    name: order-system
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ordersystem?serverTimezone=UTC&useUnicode=yes&characterEncoding=utf8
    username: root
    password: 123
